### ISSUE TITLE
12G gpu,  batchsize=2, out of memory?

### ISSUE THREAD

**Issue by tengshaofeng** [VinAIResearch/HyperInverter#5]
Thanks for your great project. When I train the second stage, I set batchsize=2, but it comes out of memory.

**Comment by di-mi-ta** [comment]
Hi, 
Thanks for your interest in our work!

Reducing the model size will help you to train HyperInverter on a GPU with limited memory. To reduce the model size, there are various ways. Decreasing batch size is one way. There is another way is modifying the argument `--hidden_dim`. As mentioned in the readme, the argument `--hidden_dim` has a large effect on the quality of the model, increasing them causes a bigger model and tends to have better quality. In the paper, we use hidden_dim=256. To make the model smaller, you can set this param small. However, setting this param too small may harm the model performance. Therefore, it is best to choose the value that balances well the model size and model performance in your computing condition.

**Comment by tengshaofeng** [comment]
> 

thanks for your reply patiently. I just want to know if it is normal for out of memory given 12G gpu batchsize=2. How can you train with batch size=8 with one gpu?

**Comment by di-mi-ta** [comment]
Our codebase does not support multi-GPUs training. For the experiments, we use 1 A100 GPU with 40GB for training all experiments and use 1 V100 GPU for speed and metric evaluation.

**Comment by tengshaofeng** [comment]
Ok，thanks



发自我的iPhone


------------------ Original ------------------
From: Dinh Minh Tan ***@***.***&gt;
Date: Mon,Jul 18,2022 11:48 AM
To: VinAIResearch/HyperInverter ***@***.***&gt;
Cc: bojohn ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [VinAIResearch/HyperInverter] 12G gpu,  batchsize=2, out ofmemory? (Issue #5)





 
Our codebase does not support multi-GPUs training. For the experiments, we use 1 A100 GPU with 40GB for training all experiments and use 1 V100 GPU for speed and metric evaluation.
